app.scheduler.interval: 100000ms
springdoc.swagger-ui.path: /swagger-ui.html
spring.liquibase.enabled: false

spring.application.name: scrapper
spring.datasource.url: jdbc:postgresql://localhost:5432/scrapper
spring.datasource.username: admin
spring.datasource.password: admin
spring.cloud.vault:
    uri: http://localhost:8200
    token: ${VAULT_TOKEN}
spring.config.import: 'vault://'
