version: '3'

services:
  postgresql:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: scrapper
    restart: unless-stopped
    networks:
      - backend

  liquibase-migrations:
    image: liquibase/liquibase:4.18
    depends_on:
        - postgresql
    command:
        - --hub-mode=off
        - --changelog-file=changelog-master.xml
        - --driver=org.postgresql.Driver
        - --url=jdbc:postgresql://postgresql:5432/scrapper
        - --username=admin
        - --password=admin
        - update
    volumes:
        - ./migrations:/liquibase/changelog
    networks:
        - backend

volumes:
  postgres-data:

networks:
  backend:
