/*
 * This file is generated by jOOQ.
 */
package ru.asvronsky.scrapperjooq.domain.tables.records;


import java.time.OffsetDateTime;

import org.jooq.Field;
import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;

import ru.asvronsky.scrapperjooq.domain.tables.Link;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LinkRecord extends UpdatableRecordImpl<LinkRecord> implements Record4<Long, String, OffsetDateTime, JSONB> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.link.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.link.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.link.url</code>.
     */
    public void setUrl(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.link.url</code>.
     */
    public String getUrl() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.link.updated_at</code>.
     */
    public void setUpdatedAt(OffsetDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.link.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(2);
    }

    /**
     * Setter for <code>public.link.website_data</code>.
     */
    public void setWebsiteData(JSONB value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.link.website_data</code>.
     */
    public JSONB getWebsiteData() {
        return (JSONB) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, String, OffsetDateTime, JSONB> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Long, String, OffsetDateTime, JSONB> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Link.LINK.ID;
    }

    @Override
    public Field<String> field2() {
        return Link.LINK.URL;
    }

    @Override
    public Field<OffsetDateTime> field3() {
        return Link.LINK.UPDATED_AT;
    }

    @Override
    public Field<JSONB> field4() {
        return Link.LINK.WEBSITE_DATA;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getUrl();
    }

    @Override
    public OffsetDateTime component3() {
        return getUpdatedAt();
    }

    @Override
    public JSONB component4() {
        return getWebsiteData();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getUrl();
    }

    @Override
    public OffsetDateTime value3() {
        return getUpdatedAt();
    }

    @Override
    public JSONB value4() {
        return getWebsiteData();
    }

    @Override
    public LinkRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public LinkRecord value2(String value) {
        setUrl(value);
        return this;
    }

    @Override
    public LinkRecord value3(OffsetDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public LinkRecord value4(JSONB value) {
        setWebsiteData(value);
        return this;
    }

    @Override
    public LinkRecord values(Long value1, String value2, OffsetDateTime value3, JSONB value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LinkRecord
     */
    public LinkRecord() {
        super(Link.LINK);
    }

    /**
     * Create a detached, initialised LinkRecord
     */
    public LinkRecord(Long id, String url, OffsetDateTime updatedAt, JSONB websiteData) {
        super(Link.LINK);

        setId(id);
        setUrl(url);
        setUpdatedAt(updatedAt);
        setWebsiteData(websiteData);
        resetChangedOnNotNull();
    }
}
