/*
 * This file is generated by jOOQ.
 */
package ru.asvronsky.scrapperjooq.domain;


import ru.asvronsky.scrapperjooq.domain.tables.Chat;
import ru.asvronsky.scrapperjooq.domain.tables.Databasechangelog;
import ru.asvronsky.scrapperjooq.domain.tables.Databasechangeloglock;
import ru.asvronsky.scrapperjooq.domain.tables.Link;
import ru.asvronsky.scrapperjooq.domain.tables.Subscription;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.chat</code>.
     */
    public static final Chat CHAT = Chat.CHAT;

    /**
     * The table <code>public.databasechangelog</code>.
     */
    public static final Databasechangelog DATABASECHANGELOG = Databasechangelog.DATABASECHANGELOG;

    /**
     * The table <code>public.databasechangeloglock</code>.
     */
    public static final Databasechangeloglock DATABASECHANGELOGLOCK = Databasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * The table <code>public.link</code>.
     */
    public static final Link LINK = Link.LINK;

    /**
     * The table <code>public.subscription</code>.
     */
    public static final Subscription SUBSCRIPTION = Subscription.SUBSCRIPTION;
}
